### ISSUE TITLE
Add .toString() as alias for default .toFormat()

### ISSUE THREAD

**Issue by Alex-Sokolov** [dinerojs/dinero.js#113]
Hi! Thanks for your work!

Is it possible to add .toString as alias for default .toFormat for dinero-values. It will be useful for logging to get default formatted value instead of object

**Comment by sarahdayan** [comment]
Hi @Alex-Sokolov and thanks for opening this.

With [v2](https://v2.dinerojs.com/docs) out, I'm not looking to add new features to v1, only maintain it for critical issues. Feel free to open a [discussion](https://github.com/dinerojs/dinero.js/discussions) to discuss this for v2!
