### ISSUE TITLE
Option to humanize large numbers

### ISSUE THREAD

**Issue by jonyeezs** [dinerojs/dinero.js#139]
**Is your feature request related to a problem? Please describe.**
When dealing with huge currency values in small confine real estate on a screen,
it would be useful to make it compact and easily identifiable by human.

For example $1,245,500 should look like $1.2M
or $1,000,000,000,000 should look like $1T

**Describe the solution you'd like**

Here's a library that does it for integers in general https://github.com/HubSpot/humanize#compactinteger.

And here's a C# version https://github.com/Humanizr/Humanizer#metric-numerals

**Describe alternatives you've considered**

**Additional context**

**Comment by sarahdayan** [comment]
Hey! I just released [Dinero.js v2 in alpha](https://v2.dinerojs.com/docs), and this is possible userland using the [`toFormat`](https://v2.dinerojs.com/docs/api/formatting/to-format) function.

For example, with a package like [`humanize-num`](https://yarnpkg.com/package/humanize-num):

```js
import { toFormat } from 'dinero.js';
import humanize from 'humanize-num';

function toHumanReadableFormat(dineroObject) {
  function transformer({ amount, currency }) {
    const symbols = {
      USD: '$',
    };

    return `${symbols[currency.code]} ${humanize(amount)}`;
  }

  return toFormat(dineroObject, transformer);
}
```

Then, you can use it to format objects:

```js
import { dinero } from 'dinero.js';
import { USD } from '@dinero.js/currencies';

import { toHumanReadableFormat } from './toHumanReadableFormat';

const d1 = dinero({ amount: 124550000, currency: USD });
const d2 = dinero({ amount: 100000000000000, currency: USD });

toHumanReadableFormat(d1); // "$ 1.2M"
toHumanReadableFormat(d2); // "$ 1T"
```

You can see it in action [here](https://codesandbox.io/s/sleepy-darwin-gj4jc?file=/main.js).
