### ISSUE TITLE
Extract currency amount occurencies from string

### ISSUE THREAD

**Issue by kevin-wad** [dinerojs/dinero.js#140]
**Is your feature request related to a problem? Please describe.**
Hi, it's not a problem but an improvement.

I am wondering if this library has a way to extract price occurencies in a string. It could be based on a regex rule, but surprisingly it seems no perfect rule already exists for this use case.
**Describe the solution you'd like**

It could be a function that takes a string as parameter and returns an array of all prices found within the string. And would be even better if there was a possibility for a callback function foreach price found. This would give possibility for new price conversion use cases, as we could use it to add additional info or replace the currency in the string
**Describe alternatives you've considered**
I am currently trying to find the best way to do it but I experience issues with the regex rules I foud, do you have any idea of a working regex rule or any other tool available ?
Thank you and best regards

**Additional context**

**Comment by kevin-wad** [comment]
Hi, finally I was able to find a solution thanks to this site: https://www.regextester.com

Best regards

**Comment by bobber205** [comment]
@kevin-wad You really not going to post your solution just the site where you came up with it on? How does that help anyone at all?
