### ISSUE TITLE
Docs mention HALF_AWAY_FROM_ZERO, reality banker's rounding?

### ISSUE THREAD

**Issue by Lukasvo** [dinerojs/dinero.js#157]
[The docs for toFormat](https://dinerojs.com/module-dinero#~toFormat) mention that amounts are rounded using the half away from zero rule by default.

However:

`Dinero({ amount: 5000 }).multiply(0.05*1.21).toFormat('0.00') === "3.02"`
while `50*0.05*1.21 === 3.025` so HALF_AWAY_FROM_ZERO should produce "3.03"

It seems like it rounds to 3.02 because that's the closest even digit.
Opposite example:

`Dinero({ amount: 15000 }).multiply(0.05*1.21).toFormat('0.00') === "9.08"`
while `150*0.05*1.21 = 9.075` so this is correct

Could it be that [Bankers rounding](http://wiki.c2.com/?BankersRounding) is used by default instead of HALF_AWAY_FROM_ZERO?

**Comment by grrowl** [comment]
It appears `globalRoundingMode` is never set, so I'm not sure how the default behaviour is meant to be applied

https://github.com/dinerojs/dinero.js/blob/develop/src/dinero.js#L63-L68

**Comment by Lukasvo** [comment]
There is also a `globalFormatRoundingMode`, which defaults to HALF_AWAY_FROM_ZERO like the docs mention, but it has no effect on the toFormat() examples mentioned above.

```
Dinero.globalFormatRoundingMode
"HALF_AWAY_FROM_ZERO"
```

**Comment by sarahdayan** [comment]
Hey @Lukasvo and sorry for the late reply.

The global rounding mode for `toFormat` is indeed `HALF_AWAY_FROM_ZERO`. If you pass your final number (`3.025`) in a Dinero representation and format it, you get the expected result:

```js
Dinero({ amount: 3025, precision: 3 }).toFormat('0.00'); // "3.03"
```

What's happening is that you're multiplying by `0.0605` first, and the `multiply` function has a rounding mode as well, but this one is `HALF_EVEN` by default. So it does `5000 * 0.0605` which gives `302.5`, then rounds it to `302`. By the time you reach `toFormat`, there's nothing left to round.

You can fix it by passing `HALF_AWAY_FROM_ZERO` to `multiply`:

```js
Dinero({ amount: 5000 }).multiply(0.05*1.21, 'HALF_AWAY_FROM_ZERO').toFormat('0.00'); // "3.03"
```

Besides, I recommend you to check out [Dinero v2](https://v2.dinerojs.com/docs) which no longer rounds across mutations, but adjusts its scale instead to preserve the full precision.
