### ISSUE TITLE
Read Full Documentation Link on npm broken

### ISSUE THREAD

**Issue by gauvins** [dinerojs/dinero.js#166]
On the npm page https://www.npmjs.com/package/dinero.js the "Read Full Documentation" link near the bottom of the page 

![image](https://user-images.githubusercontent.com/311992/87341202-96083600-c51f-11ea-9501-f24011f6f6cb.png)

points to https://sarahdayan.github.io/dinero.js/module-Dinero.html which is reported as broken.

![image](https://user-images.githubusercontent.com/311992/87341226-a3bdbb80-c51f-11ea-9422-f769f0fbdae1.png)

Probably want to replace it with the real documentation link: 

https://dinerojs.com/

macOS Chrome Version 83

**Comment by mylastore** [comment]
Correct link should be this. `https://dinerojs.com/module-dinero`

**Comment by rohansp** [comment]
@mylastore @gauvins I believe correct link is already corrected in README.md. [dinero-docs]: https://dinerojs.com/module-dinero although  Read full documentation on the live version still points to https://sarahdayan.github.io/dinero.js/module-Dinero.html @sarahdayan Is the latest version deployed?

**Comment by sarahdayan** [comment]
Hey, thanks for reporting and sorry for the late reply.

I just deployed 1.9.0, so this is fixed now.
