### ISSUE TITLE
How can i use "," instead of "."

### ISSUE THREAD

**Issue by gabrielvrl** [dinerojs/dinero.js#173]
In some countries is more common to use "," instead of "." to separate the decimals

**Comment by sarahdayan** [comment]
If you're using v1, I recommend checking the docs on [`toFormat`](https://dinerojs.com/module-dinero#~toFormat) to see how you can specify a locale that will automatically give you the right format.

If you're using [v2](https://v2.dinerojs.com/docs), [`toFormat`](https://v2.dinerojs.com/docs/api/formatting/to-format) leaves you full control over formatting. You can see how to build your own formatted on top of the Intl API by following [this guide](https://v2.dinerojs.com/docs/advanced/formatting-in-a-multilingual-site).
