### ISSUE TITLE
I'm getting 'price.add is not a function'

### ISSUE THREAD

**Issue by gabrielvrl** [dinerojs/dinero.js#174]
summarizing my code:
```
import Dinero from "dinero.js";

const price = Dinero({ amount: 5000 }).toFormat();
import Dinero from "dinero.js";
```

dont know what i'm doing wrong to get the error 'price.add is not a function'

**Comment by sarahdayan** [comment]
Hi Gabriel. I'm unsure of what the issue is without a reproducible example, but your second import in line 4 is definitely problematic. Can you try removing it and try again?

If the error persists, please share a reproducible example in a [CodeSandbox](https://codesandbox.io/).

**Comment by sarahdayan** [comment]
This issue has been stale for almost a year so I'll close it for now.

Don't hesitate to check out [Dinero.js v2](https://v2.dinerojs.com/docs) if you still need to manipulate money!
