### ISSUE TITLE
Links on the docs page cause a redirect

### ISSUE THREAD

**Issue by galagora** [dinerojs/dinero.js#184]
On your website, internal links are of the form `module-Dinero.html#<anchor>`, which is 301 redirected to `module-dinero#~<anchor>`, causing an annoying page load every time you click a link. As a quick fix, you could probably add something like this:
```bash
find ./docs -type f -name "*.html" -exec sed -i'' -e 's/module-Dinero.html/module-dinero/g' {} +
```
to your NPM `docs` script.

**Comment by galagora** [comment]
BTW if you want to fix this client-side, you can use this userscript:
```javascript
// ==UserScript==
// @require     https://cdnjs.cloudflare.com/ajax/libs/cash/8.1.0/cash.min.js
// ==/UserScript==

$("a").each(function(){const hr=$(this).attr("href");const mod=hr.match(/#.+/);if(mod){$(this).attr("href", "module-dinero"+mod[0])}})
```

**Comment by sarahdayan** [comment]
Thanks for opening this. Now that v2 is out, Dinero.js v1 will move to maintenance mode so unless there's a blocking bug and it concerns the code, I won't merge new PRs.

Thanks again and hope to see you contribute on v2!
