### ISSUE TITLE
Incorrect result with convertPrecision from 6 to 2 decimals using HALF_EVEN

### ISSUE THREAD

**Issue by leolara** [dinerojs/dinero.js#187]
**Describe the bug**

When I use converPrecision from 6 to 2 decimals using HAL_EVEN I do not get the expected result

**To reproduce**

If I do: 

`Dinero({ amount: 1500, currency: 'EUR', precision: 5 }).convertPrecision(2, 'HALF_EVEN').toObject()`

I get:

`{ amount: 2, currency: 'EUR', precision: 2 }`

Which I think it is **correct**, as 0.01500 should round HALF_EVEN to 0.02

However If I do:

`Dinero({ amount: 15000, currency: 'EUR', precision: 6 }).convertPrecision(2, 'HALF_EVEN').toObject()`

It results in `{ amount: 1, currency: 'EUR', precision: 2 }` which I think it is **incorrect**.

**Expected behavior**

It should return `{ amount: 2, currency: 'EUR', precision: 2 }`

**Screenshots**

```
$ ts-node
> const Dinero = require('dinero.js')
'use strict'
> Dinero({ amount: 1500, currency: 'EUR', precision: 5 }).convertPrecision(2, 'HALF_EVEN').toObject()
{ amount: 2, currency: 'EUR', precision: 2 }
> 
(To exit, press ^C again or ^D or type .exit)
> Dinero({ amount: 15000, currency: 'EUR', precision: 6 }).convertPrecision(2, 'HALF_EVEN').toObject()
{ amount: 1, currency: 'EUR', precision: 2 }
```

**Node**

Calling from ts-node v9.0.0 in Linux

**Additional context**

 dinero.js@1.8.1

**Comment by leolara** [comment]
I also see the error when converting from precision 7 to 2. However, from precision 8 to 2, also I get the correct answer

**Comment by leolara** [comment]
I think I found a solution, the problem is that pow(10, 2-6) and pow(10, 2-7) give incorrect float point numbers that are off.

If you instead of using multiplication always, use division with rounding when you go from larger precision to smaller precision, then you would always do positive powers of 10, eliminating those annoying float points errors

**Comment by sarahdayan** [comment]
Hi @leolara, and sorry for the late reply.

You're right, this is a bug and it can be fixed by using a division by `pow(10, precision-newPrecision)` when the new precision is smaller, and a multiplication with `pow(10, newPrecision-precision)` when it's larger.

If you're up to it, you can open a PR to fix it. Otherwise, I'll do it.

**Comment by artfuldev** [comment]
Thank you so much @sarahdayan !

I don't think I can add labels myself to a PR. I've attempted a PR but it fails the actions set up. The test and build scripts seem to work on my machine though. I've added the exact test case from this issue to the PR #424 .

**Comment by sarahdayan** [comment]
Yeah it's normal the build is failing on the PR, `v1` has no CI. I will check it on my machine this week end and approve it if all is well. Thanks for contributing 🙂

Also added the label.

**Comment by sarahdayan** [comment]
Thanks @artfuldev, this is approved, merged, and published: https://www.npmjs.com/package/dinero.js/v/1.9.1

I also added you as contributors on [`v1`](https://github.com/dinerojs/dinero.js/tree/v1#contributors) and [`main`](https://github.com/dinerojs/dinero.js/tree/main#-contributors).

Good luck with Hacktoberfest!
