### ISSUE TITLE
currencyFromSymbol util

### ISSUE THREAD

**Issue by imsergiobernal** [dinerojs/dinero.js#194]
I'm parsing websites so, what I usually get is an string that I must normalize from symbol currencies.

I think that some static utils would become useful over here, like a static method
```ts
currencyFromSymbol(symbol: string): Dinero.Currency
```

What do you think?

**Comment by sarahdayan** [comment]
Hey! Similar to #67, if you're willing to use [Dinero.js v2](https://v2.dinerojs.com/docs), you can build your own utility for this.

```js
import { dinero } from 'dinero.js';
import { USD, EUR } from '@dinero.js/currencies';

const symbols = {
  '$': USD,
  '€': EUR,
};

function currencyFromSymbol(symbol) {
  return symbols[symbol];
}
```

It makes more sense to keep this userland, as you're the one knowing what currencies you use in your application.
