### ISSUE TITLE
Chrome 88.0.4324.93 always includes currency code in toFormat()

### ISSUE THREAD

**Issue by grrowl** [dinerojs/dinero.js#201]
**Describe the bug**

In Chrome 88.0.4324.93 on Android 10, the currency code is always included in the result of `.toFormat()`, regardless of locale.

**To reproduce**

Codesandbox: https://codesandbox.io/s/testing-dinerojs-forked-8ollc?file=/src/index.js

```tsx
{Dinero.globalLocale}

bare: {Dinero({ amount: 500 }).toFormat()}

AUD: {Dinero({ amount: 500, currency: "AUD" }).toFormat()}
AUD in AU: {Dinero({ amount: 500, currency: "AUD" }).setLocale("en-AU").toFormat()}
AUD in US: {Dinero({ amount: 500, currency: "AUD" }).setLocale("en-US").toFormat()}

USD: {Dinero({ amount: 500, currency: "USD" }).toFormat()}
USD in AU: {Dinero({ amount: 500, currency: "USD" }).setLocale("en-AU").toFormat()}
USD in US: {Dinero({ amount: 500, currency: "USD" }).setLocale("en-US").toFormat()}
```

### Chrome 87 & 88.0.4324.96 (macos)

![image](https://user-images.githubusercontent.com/907140/105301694-3ba70b00-5c0f-11eb-8f67-85078ebd3fa7.png)

### Chrome 88.0.4324.93 (android 10)

![image](https://user-images.githubusercontent.com/907140/105301160-1914f200-5c0f-11eb-9936-277f0f182e15.png)

**Expected behavior**

Especially when no locale or currency is specified (`Dinero({ amount: 500 }).toFormat()`), the currency code should not be included in the output of `toFormat()`

**Browser**

- OS: Android 10
- Browser: Chrome 88.0.4324.93 (latest stable)

**Additional context**

I haven't been able to reproduce on Chrome Version 88.0.4324.96 (MacOS), nor in Node.js

**Comment by grrowl** [comment]
I've tracked it down to the [use of `toLocaleString()` in the `toFormat` function](https://github.com/dinerojs/dinero.js/blob/develop/src/dinero.js#L875), Chrome must have changed their behaviour. Oh dear.

**Comment by sarahdayan** [comment]
Hey @grrowl! This is exactly what's happening, the [Intl API](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Intl) is implemented differently depending on the platform.

**Relying on this API in v1 was a mistake, I've fixed it in [v2](https://v2.dinerojs.com/docs).** In v2, [`toFormat`](https://v2.dinerojs.com/docs/api/formatting/to-format) gives you full control over formatting. You can still [use the Intl API if you want](https://v2.dinerojs.com/docs/advanced/formatting-in-a-multilingual-site), but at least that's not hidden within the library and it's a conscious choice on your end.
