### ISSUE TITLE
Support for BigInt?

### ISSUE THREAD

**Issue by RIP21** [dinerojs/dinero.js#204]
**Is your feature request related to a problem? Please describe.**

Being able to construct with BigInts in the same way as I can construct with int.
So `Dinero({ amount: 100000n, currency: "USD" })` works and not fails.

**Describe the solution you'd like**

Support for [BigInt](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/BigInt)?

**Additional context**
Some fields in the database I store are in BigInt, specifically amount so I get it from database as a BigInt e.g. 100000n, e.g. proper `bigint` (as per Typescript type primitive type notation). Both the implementation fails as well as the Typescript types are unhappy with `bigint` which makes sense.

**Comment by sarahdayan** [comment]
Hey! I just released [Dinero.js v2 in alpha](https://v2.dinerojs.com/docs), which provides a `bigint` calculator out of the box.

You can check out [this guide](https://v2.dinerojs.com/docs/advanced/using-different-amount-types#using-dinero-with-bigint) on how to use the library with `bigint`.
