### ISSUE TITLE
Documentation on various rounding modes light. 

### ISSUE THREAD

**Issue by ppanthony** [dinerojs/dinero.js#205]
Documentation unclear. 

The documentation currently states: 

```
roundingMode | String | <optional> | 'HALF_AWAY_FROM_ZERO' | The rounding mode to use: 'HALF_ODD', 'HALF_EVEN', 'HALF_UP', 'HALF_DOWN', 'HALF_TOWARDS_ZERO', 'HALF_AWAY_FROM_ZERO' or 'DOWN'.
-- | -- | -- | -- | --
```

However, each of these are not illustrated in the docs. I would like to see the output from each of these presented in the documentation so I don't have to use guess work to figure out what they do. The examples provided could be enhanced with additional documentation samples surrounding the rounding modes.

This is specifically on this section of the docs: https://dinerojs.com/module-dinero#~toFormat

**Comment by sarahdayan** [comment]
Hey @ppanthony!

Rounding modes in Dinero.js use standard naming, you can find detailed behavior [here](https://wikipedia.org/wiki/Rounding#Rounding_to_integer).
