### ISSUE TITLE
dinero.min.js:1 Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by robskrob** [dinerojs/dinero.js#207]
**Describe the bug**

When I load dinero as a script in my HTML head, I am seeing this error
```
Uncaught ReferenceError: module is not defined
```
![Screen Shot 2021-03-22 at 4 24 29 PM](https://user-images.githubusercontent.com/4349424/112053741-152c2000-8b2b-11eb-808f-ba540a8d40d0.png)

**To reproduce**

1. Load the below html file 
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>title</title>
    <script src="https://cdn.jsdelivr.net/npm/dinero.js@1.8.1/build/cjs/dinero.min.js"></script>
  </head>
  <body>

  </body>
</html>
```
2. View console error

**Expected behavior**

I expect to see no JS error

**Screenshots**

**Browser**

- OS: macOS
- Browser Chrome
- Version 88.0.4324.192

**Additional Context**
I got the above JS script from [here](https://www.jsdelivr.com/package/npm/dinero.js?path=build&tab=collection)

Also what I find strange is that the Dinero JS API in the browser is working just fine for me. I can use all the libraries features -- despite the browser reporting the error.

**Comment by sarahdayan** [comment]
You're trying to import the CommonJS module in the browser. CommonJS is specific to Node.js, which is why you're getting this error.

You need to import the [UMD build](https://cdn.jsdelivr.net/npm/dinero.js@1.8.1/build/umd/dinero.min.js) instead.
