### ISSUE TITLE
Convert Currency never resolves 

### ISSUE THREAD

**Issue by Justinohallo** [dinerojs/dinero.js#210]
**Describe the bug**

I have copied the code from the currency conversion section of the documentation, and no matter what I do I cannot get the promise from .convert to resolve correctly. I would like to simply assign the result of the conversion to a variable rather than reassigning a variable from within the scope of the async function. 

**To reproduce**

```
const rates = {
  rates: {
    USD: 1.25971,
    CAD:0.7938335013614244
  }
}

const value =  Dinero({ amount: 500 })
  .convert('USD',     {endpoint: new Promise(resolve => resolve(rates))}
)
  .then(dinero => dinero.getCurrency()
  )
  .catch(err => {
    // handle errors
  })
console.log(value)
```

**Expected behavior**

I would expect to receive the string value of 'USD'. Right now I just receive an unresolved promise. No combination of async/await or .then will produce this value in a return statement. 

**Screenshots**

**Browser**

- OS: macOS
- Browser Chrome
- Version 89

**Additional context**

**Comment by Justinohallo** [comment]
Was able to get it to work using top level await, but feel like I am missing something as I am simply following the docs. 

`let amount = await (async () => {
  const price = await Dinero({ amount: 500 }).convert('EUR', {
    endpoint: new Promise(resolve => resolve(rates))
  })
  return await price.getCurrency() // returns 'EUR'
})()`

**Comment by sarahdayan** [comment]
Hey @Justinohallo! Your initial code snippet behaves like `Dinero.convert` is synchronous. You can't assign the return value of `Dinero.convert` to your `value` variable—this variable will always be equal to a resolved promise.

To access the value, you either need to do it in `then`, or use `async`/`await`, [as explained in the docs](https://dinerojs.com/module-dinero#~convert).

```js
let value = null;

Dinero({ amount: 500 })
  .convert('USD', { endpoint: new Promise((resolve) => resolve(rates)) })
  .then((dinero) => {
    value = dinero;
  });

console.log(value);

// or

(async () => {
  const value = await Dinero({ amount: 500 }).convert('USD', {
    endpoint: new Promise((resolve) => resolve(rates)),
  });

  console.log(value);
})();
```
