### ISSUE TITLE
How to compare the objects with jest

### ISSUE THREAD

**Issue by dmitryusikriseapps** [dinerojs/dinero.js#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Our application uses `Dinero.js` under the hood. But it doesn't work as expected when we cover our parsers with jest. Let me provide you with a couple of examples.

toEqual:
<img width="975" alt="Screenshot 2021-07-23 at 15 47 04" src="https://user-images.githubusercontent.com/45354628/126783657-b88c0eb6-68d2-446b-9d75-73c04f7bb4af.png">

toMatchObject:
<img width="979" alt="Screenshot 2021-07-23 at 15 47 18" src="https://user-images.githubusercontent.com/45354628/126783668-f2df44b9-c6c8-48b9-8516-cca95804ea1c.png">

toContainEqual:
<img width="1025" alt="Screenshot 2021-07-23 at 15 47 30" src="https://user-images.githubusercontent.com/45354628/126783680-7714d0a1-19eb-4616-9e1d-664cf553e188.png">

Could you please provide us with some examples, how to compare the objects with jest?

### Expected behavior

Jest comparison functions should work as expected.

### Steps to reproduce

1. Create a typescript interface where one of the fields has the `Money` type from `Dinero.js`.
2. Create 2 similar objects.
3. Try to compare them with jest.

### Version

2.0.0alpha5

### Environment

Expo SDK 39

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarahdayan** [comment]
Hey @dmitryusikriseapps! It would be helpful for me to see your actual tests, but from what Jest is telling you, it looks like you should first [snapshot](https://v2.dinerojs.com/docs/api/formatting/to-snapshot) your Dinero objects before comparing them.

Let me know how this work.

**Comment by dmitryusikriseapps** [comment]
Hey @sarahdayan, thank you for the quick response.
Unfortunately, I can't provide the full code of the application since it's under NDA, but it looks like this:

```
type Money = Dinero<number>;

type PayRate = {
    name: string;
    description: string;
    rate: Money;
};

const payRate1: PayRate = {
    name: 'name1',
    description: 'description1';
    rate: dinero({ amount: 5000, currency: USD }),
}

const payRate2: PayRate = {
    name: 'name2',
    description: 'description2';
    rate: dinero({ amount: 10000, currency: USD }),
}

expect(payRate1).toEqual(payRate2);
```

**Comment by sarahdayan** [comment]
Got it. In that case you should stringify first, an that'll do the trick:

```js
expect(JSON.stringify(payRate1)).toEqual(JSON.stringify(payRate2));
```

**Comment by dmitryusikriseapps** [comment]
@sarahdayan Thank you, that works!
