### ISSUE TITLE
npm scripts - OS compatibility

### ISSUE THREAD

**Issue by frobinsonj** [dinerojs/dinero.js#41]
Hi, I have recently started using Dinero and I am interested in potentially contributing where I can. However, I have encountered some issues trying to run the `build` and `docs` scripts. This is due me being on Windows (no `rm` command, backslashes in paths, etc).

These are easy fixes so I have no problems getting on, I would just like to suggest editing these scripts to allow for compatibility across operating systems.

`rm -rf` can be replaced with something like [del-cli](https://www.npmjs.com/package/del-cli) but I am unsure how to adjust paths to work for all. Maybe something like [run-script-os](https://www.npmjs.com/package/run-script-os) would be a good solution if you're interested in this suggestion.

Thanks :)

**Comment by sarahdayan** [comment]
Hi @frobinsonj, I'm definitely interested in making it easier for more users to play with and potentially contribute to this project. Feel free to open a PR if you want to tackle it sooner than I can.
