### ISSUE TITLE
[Bug]: v2 isDinero?

### ISSUE THREAD

**Issue by mmahalwy** [dinerojs/dinero.js#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Is there a way to determine if object is from Dinero? Similar to how moment and dayjs do it: 
https://day.js.org/docs/en/query/is-a-dayjs

### Expected behavior

For there to be a method for checking if object is a Dinero object

### Steps to reproduce

See above

### Version

2.0.0-alpha8

### Environment

Node

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mmahalwy** [comment]
Ideally, it'd respond to `instanceof`

**Comment by sarahdayan** [comment]
Hey @mmahalwy, this topic has been discussed [here](https://github.com/dinerojs/dinero.js/discussions/237).

I'll close this ticket since this isn't a bug, feel free to continue the conversation over there.
