### ISSUE TITLE
[Bug]: Incorrect multiply with scale example in the the documentation 

### ISSUE THREAD

**Issue by johnhooks** [dinerojs/dinero.js#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The example on the website of multiplying tax rates doesn't work [website/data/docs/core-concepts/scale.mdx](https://github.com/dinerojs/dinero.js/blob/7b22949c0717592e4fc404a20e3e7002d8e6835c/website/data/docs/core-concepts/scale.mdx)

### Expected behavior

I couldn't get the example to work. It wouldn't use the scale `{ scale: 3 }`. After looking at the source file [packages/core/src/api/multiply.ts](https://github.com/dinerojs/dinero.js/blob/main/packages/core/src/api/multiply.ts), I was able to get it to work if line 5 is written as follows:

```js
const tax = multiply(price, { amount: 55, scale: 3 })
```

### Steps to reproduce

```js
import { dinero, add, multiply, toSnapshot } from 'dinero.js';
import { EUR } from '@dinero.js/currencies';

const price = dinero({ amount: 1995, currency: EUR });
const tax = multiply(price, 55, { scale: 3 }); // ** I think this should call multiply(price, { account: 55, scale: 3 })
const total = add(price, tax);
```

### Version

2.0.0-alpha-8

### Environment

Node.js v16.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnhooks** [comment]
Oh, and by the way, if I am correct and it needs to be changed, I would love the opportunity to actually do the pr. I haven't done one before though, might need some hand holding.

**Comment by johnhooks** [comment]
I may need some help on how to word the conventional commit. Also, after further reading of the dinero.js documentation,I saw the same issue a little further down on the same page, if this is a change you want to make, I can search through the rest of the documentation and find any similar instances.

**Comment by sarahdayan** [comment]
Hey @johnhooks, you're right these are documentation mistakes. I'll check your PR and will help you out on the confusing parts.

**Comment by johnhooks** [comment]
@sarahdayan after more research I am pretty sure I shouldn't have made the PR from the main branch of my fork, is that correct? And if so, what would be the best way to fix the mistake?

**Comment by sarahdayan** [comment]
@johnhooks Not at all a problem to work from a fork!

**Comment by johnhooks** [comment]
@sarahdayan sorry I just want to double check before trying again, was I supposed to create a branch in my fork of dinero.js, make the changes, commit and create a PR from that branch into the main of branch of dinero.js? Because right now the PR I opened is from the main branch of my fork... boy I hope that makes sense.

**Comment by sarahdayan** [comment]
@johnhooks Your fork's `main` branch can be considered as a different "branch", so it's no problem at all that you commited directly on `johnhooks:main`; it's still a different branch than `dinerojs:main`. As you can see on your PR, [the diff is correct](https://github.com/dinerojs/dinero.js/pull/487/files).

In other words, your PR is fine 👍 I'll let you address [my comments](https://github.com/dinerojs/dinero.js/pull/487#issuecomment-967164567), then we'll be able to merge.

Thanks for your help!

**Comment by johnhooks** [comment]
Thanks @sarahdayan for helping me figure that out, I'm stoked to have made my first PR!
