### ISSUE TITLE
[Bug]: @dinero.js/currencies not behaving

### ISSUE THREAD

**Issue by mishrasatyam** [dinerojs/dinero.js#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
import { USD } from '@dinero.js/currencies'
         ^^^
SyntaxError: Named export 'USD' not found. The requested module '@dinero.js/currencies' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@dinero.js/currencies';
const { USD } = pkg;
```

### Expected behavior

Work properly withourt above error

### Steps to reproduce

1. npm init -y
2. add `"type":"module"` in package.json
3. create index.js with `import { USD } from '@dinero.js/currencies'`
4. node index.js

### Version

@dinero.js/currencies 2.0.0-alpha.1 dinero.js 2.0.0-alpha.8

### Environment

Node js v16.13.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarahdayan** [comment]
Hey @mishrasatyam,

Your `@dinero.js/currencies` dependency is outdated, and mismatches your `dinero.js` dependency. Please use 2.0.0-alpha.8 for both, it will solve your issue.
