### ISSUE TITLE
[Bug]: decimal points throw error

### ISSUE THREAD

**Issue by mishrasatyam** [dinerojs/dinero.js#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```js
import { dinero, add } from 'dinero.js';
import pkg from '@dinero.js/currencies';
const {USD} = pkg
dinero({amount:45,currency:USD}) // no error
dinero({amount:45.99,currency:USD}) //throws Error: [Dinero.js] Amount is invalid
```
gives error
```
/home/satyam/dinero/node_modules/.pnpm/dinero.js@2.0.0-alpha.8/node_modules/dinero.js/dist/cjs/index.development.js:23
    throw new Error("[Dinero.js] ".concat(message));
          ^

Error: [Dinero.js] Amount is invalid.
```

### Expected behavior

No error for decimal values

### Steps to reproduce

1. node js v16.13.0
2. add 
```js
import { dinero, add } from 'dinero.js';
import pkg from '@dinero.js/currencies';
const {USD} = pkg
dinero({amount:45,currency:USD}) // no error
dinero({amount:45.99,currency:USD}) //throws Error: [Dinero.js] Amount is invalid
```
to index .js

3. node index.js
4. get error

### Version

@dinero.js/currencies 2.0.0-alpha.1 dinero.js 2.0.0-alpha.8

### Environment

node js v16.13.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mishrasatyam** [comment]
Reading more docs made it clear about scale, but a better error message would be more helpful.

**Comment by sarahdayan** [comment]
Hey @mishrasatyam.

The documentation is explicit regarding the need to only use integer values. Regarding the error message, what would you have in mind? Keep in mind that longer error strings negatively impact the build size, which is also why I keep them short.
