### ISSUE TITLE
Feature request: get subUnits method

### ISSUE THREAD

**Issue by bel0v** [dinerojs/dinero.js#627]
There is a `hasSubUnits()` method that returns a boolean, but no API to get the actual value for the sub units.
For reference, my use case: we've got a price label that looks like this —
<img width="217" alt="Screenshot 2022-04-25 at 11 49 19" src="https://user-images.githubusercontent.com/2889382/165054418-7bb1e3b1-bd4e-4d68-a721-bb8b6f91da84.png">
 I need to render sub units separately for this.

Thanks!

**Comment by bel0v** [comment]
Currently in my project I implemented it like this:
```javascript
const getSubUnits = (money: Dinero<number>) => {
  const { amount, currency, scale } = money.toJSON()
  const { calculator } = money
  return calculator.modulo(amount, calculator.power(currency.base, scale))
}
```
— basically it mimics the hasSubUnits implementation

**Comment by johnhooks** [comment]
@bel0v this is being considered in [PR #309](https://github.com/dinerojs/dinero.js/pull/309)

The new [toUnits](https://github.com/dinerojs/dinero.js/blob/45b5e671f70c07fc2588613006e6919fc95808d2/packages/dinero.js/src/api/toUnits.ts) function will return a tuple of `[major, minor]`.

So it would be trivial to get just the sub units.

```js
const [,subUnits] = toUnits(dineroObject);
```

**Comment by sarahdayan** [comment]
Hey @bel0v, cool use case! The [`v2.0.0-alpha.11`](https://github.com/dinerojs/dinero.js/releases/tag/v2.0.0-alpha.11) release provides [`toUnits`](https://v2.dinerojs.com/docs/api/formatting/to-units) as mentioned by @johnhooks.
