### ISSUE TITLE
Project Maintenance Status?

### ISSUE THREAD

**Issue by michaelhays** [dinerojs/dinero.js#644]
Hey @sarahdayan, thanks for the awesome work on this library. I noticed that non-bot contributor work has [fallen off pretty significantly](https://github.com/dinerojs/dinero.js/graphs/contributors) since around October 2021, and that the last 2.0 alpha was released back in [August 2021](https://www.npmjs.com/package/dinero.js?activeTab=versions).

Is there a plan to come back and release a stable 2.0 version? (I know open source work can be very hard to prioritize, so no pressure -- just trying to understand where the library is at.)

It looks like the only JavaScript alternative that comes close to implementing [Martin Fowler's money pattern](https://martinfowler.com/eaaCatalog/money.html) is https://github.com/scurker/currency.js, though I really prefer the Dinero.js approach, and currency.js has similarly had a [contribution drop-off](https://github.com/scurker/currency.js/graphs/contributors) since mid-2021.

**EDIT:** Sorry, just realized this should really be a discussion instead of an issue. [This discussion](https://github.com/dinerojs/dinero.js/discussions/618) asks about the v2 release as well. I'll leave this issue open in case that discussion was missed back in April.

**Comment by ndfnd** [comment]
bump :(

**Comment by sarahdayan** [comment]
Hey everyone and thanks for your interest. Let's keep the conversation going in https://github.com/dinerojs/dinero.js/discussions/618.
