### ISSUE TITLE
[Bug]: missing ANG export 

### ISSUE THREAD

**Issue by tzii** [dinerojs/dinero.js#651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

can not import {ANG} from "@dinero.js/currencies"

### Expected behavior

import {ANG} from "@dinero.js/currencies"

### Steps to reproduce

import {ANG} from "@dinero.js/currencies"

### Version

2.0.0-alpha.8

### Environment

Node v16.15.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarahdayan** [comment]
Hey, this is fixed in [v2.0.0-alpha.9](https://github.com/dinerojs/dinero.js/releases/tag/v2.0.0-alpha.9).
