### ISSUE TITLE
[Bug]: toFormat / toSnapShot (any method that use power method) with BigInts throws an error

### ISSUE THREAD

**Issue by AbdlrahmanSaberAbdo** [dinerojs/dinero.js#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
import { calculator } from '@dinero.js/calculator-bigint';
import { createDinero, add, toFormat } from 'dinero.js';
import { USD } from '@dinero.js/currencies';

const dineroBigint = createDinero({ calculator });

const d1 = dineroBigint({ amount: 500n, currency: USD });
const d2 = dineroBigint({ amount: 100n, currency: USD });

add(d1, d2); 
toFormat(sum, ({ amount, currency }) => `${amount} ${currency.code}`)
```
And it gets the following error: 
```
export const power: BinaryOperation<bigint> = (base, exponent) => {
                                                     ^
TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at Object.d [as power] (/Users/abdlrahman/Desktop/develop/Exnaton/Repos/billing/node_modules/@dinero.js/calculator-bigint/src/api/power.ts:11:54)
```

After debugging the issue coming from `power` method, we call `toFormat` method which is call `toUnits` method which is call `power` method.

if you tried to write `calculator.power(2n, 3n)` will gave the same error.

### Expected behavior

Print the full object like this 
```
{
  amount: 5055,
  currency: { code: 'EUR', base: 10, exponent: 2 },
  scale: 2
}
```

**Note**
The same problem will arise when using any method use `power` method, like `toSnapshot`

### Steps to reproduce

https://codesandbox.io/s/xenodochial-wilbur-2ib1vp?file=/main.js

### Version

2.0.0-alpha.10

### Environment

v16.17.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarahdayan** [comment]
Hey @AbdlrahmanSaberAbdo, I noticed in your sandbox that you're using `@dinero.js/calculator-bigint2.0.0-alpha.2` instead of `2.0.0-alpha.10`.

The sandbox isn't set up to support bigints so I recreated your reproduction in a Stackblitz Node.js sandbox, which seems to work fine: https://stackblitz.com/edit/node-mewoy1?file=index.mjs

**Comment by AbdlrahmanSaberAbdo** [comment]
> Hey @AbdlrahmanSaberAbdo, I noticed in your sandbox that you're using `@dinero.js/calculator-bigint2.0.0-alpha.2` instead of `2.0.0-alpha.10`.
> 
> The sandbox isn't set up to support bigints so I recreated your reproduction in a Stackblitz Node.js sandbox, which seems to work fine: https://stackblitz.com/edit/node-mewoy1?file=index.mjs (run `node index.mjs` in the terminal).

Ohh, thank you so much for pointing out this, so I'll close the issue

**Comment by AbdlrahmanSaberAbdo** [comment]
For anyone that may face the same problem, be aware when you run `npm i @dinero.js/calculator-bigint` it'll install `@dinero.js/calculator-bigint2.0.0-alpha.2` by default so you need to specify the version which is `2.0.0-alpha.10`
