### ISSUE TITLE
ci(turbo): use GitHub Actions to take advantage of TurboRepo cache

### ISSUE THREAD

**Issue by johnhooks** [dinerojs/dinero.js#684]
@sarahdayan check this out [.github/workflows/test.yml](https://github.com/johnhooks/dinero.js/blob/5eb73bf4f591ba03f65fcedb93f67aab1fe4d427/.github/workflows/test.yml). The initial run of this workflow took 3m 11s, the rerun took **43s**! Because every step of `lint`, `test` and `build` were cache hits!

[ci/add-github-workflow](https://github.com/johnhooks/dinero.js/tree/ci/add-github-workflow)

<img width="552" alt="Screen Shot 2022-11-29 at 2 03 45 PM" src="https://user-images.githubusercontent.com/20690965/204658433-6b693277-6ade-4b12-82e3-10c4a93ec749.png">

**Comment by johnhooks** [comment]
This is an example of what the checks look like in a [Pull Request](https://github.com/johnhooks/dinero.js/pull/15). 

@sarahdayan If you're not interested I can close this issue. I was just excited that I could start running CI on my own fork without CircleCI, which is a interesting benefit of GitHub Actions over CircleCI.

**Comment by johnhooks** [comment]
I have gotten a CI run that doesn't have any source code changes down to around 1 minute.

[Here is a link to an action run](https://github.com/johnhooks/dinero.js/actions/runs/3602658355) for a PR in my fork to add Github Actions.

**Comment by sarahdayan** [comment]
That's really great, and I'd love to move away from CircleCI to GitHub Actions, it's a lot easier for contributors and benefits from the large ecosystem of existing actions.

We can probably tackle this once #667 is merged, wdyt?

**Comment by johnhooks** [comment]
@sarahdayan sounds great, this is based on the that branch, so finishing that one off makes perfect sense.

**Comment by johnhooks** [comment]
This test PR I have against my fork shows just how cool moving to Actions will be. Contributors will get all the same information about build checks inside their own forks, especially if they add their own repo to Vercel.

https://github.com/johnhooks/dinero.js/pull/15
