### ISSUE TITLE
[Bug]: Inferred return values of some core api functions are `any`

### ISSUE THREAD

**Issue by johnhooks** [dinerojs/dinero.js#695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Inferred return types of the following functions is `any`
- safeAdd
- safeAllocate
- safeCompare

### Expected behavior

Return types of the following functions need to be explicitly typed because the type checker isn't able to do it.
- safeAdd
- safeAllocate
- safeCompare

### Steps to reproduce

1. examine return type in editor

### Version

2.0.0-alpha.12

### Environment

Node.js 16.13.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnhooks** [comment]
I was looking into how to optimize the calculator functions by taking advantage of the closures in the core functions, but in the process I noticed this issue in #694.

**Comment by johnhooks** [comment]
I think using explicit return types through out the whole project would be helpful, as previously discussed.

**Comment by johnhooks** [comment]
It looks like the types are right in the declarations. I'll keep digging.

**Comment by sarahdayan** [comment]
It's probably coming from your editor after making changes. Try cleaning up your staging area, re-run `yarn` and restart the TypeScript server, and it should be fine.

Here's what I have on `main`:

<img width="853" alt="Capture d’écran 2022-12-12 à 10 23 17" src="https://user-images.githubusercontent.com/5370675/207009454-0227bd3e-ae0e-4ffb-8aba-a9556fdacfaf.png">
<img width="863" alt="Capture d’écran 2022-12-12 à 10 23 34" src="https://user-images.githubusercontent.com/5370675/207009466-2ea6183f-67d3-4e90-8566-02b1eaaf493f.png">
<img width="853" alt="Capture d’écran 2022-12-12 à 10 24 13" src="https://user-images.githubusercontent.com/5370675/207009473-bd2db5b2-bdf8-4c38-935a-b1ce438ac6df.png">

Closing for greenkeeping but feel free to reopen if it persists.
