### ISSUE TITLE
Currency code to Currency helper

### ISSUE THREAD

**Issue by Cedric1994** [dinerojs/dinero.js#700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There is currently no way to get a Currency from a currency code. 

### Expected behavior

A helper allowing the get a currency from the currency code.

It would allow anyone working with multiple ISO 4317 currencies to get the desired currency without having to implement theme-self a switch case on the currency code.

`getCurrency('USD') // returns Dinero USD object`

### Steps to reproduce

This is not a bug but a feature proposal

### Version

2.0.0-alpha.11

### Environment

all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnhooks** [comment]
The logic behind not having currency getter is explained in this issue #636.

It should be trivial to write a wrapper function for your specific use case.
