### ISSUE TITLE
Is it possible to add custom currencies at runtime?

### ISSUE THREAD

**Issue by thekevinbrown** [dinerojs/dinero.js#71]
**Is your feature request related to a problem? Please describe.**

We use this library to represent payments in AUD and USD in our app. We also have an in-app currency, and it'd be awesome if I could represent it the same way as I represent AUD and USD.

**Describe the solution you'd like**

Something like:

```
Dinero.addCurrency({
  code: 'IN-GAME',
  precision: 2,
  symbol: 'P',
});
```

and then

```
const amount = Dinero({ amount: 500, currency: 'IN-GAME' });
const total = amount.add(Dinero({ amount: 10, currency: 'IN-GAME' });
console.log(total.toFormat('$0.00'))
// -> P5.10
```

**Describe alternatives you've considered**

We could pretend the in-game currency is some other existing currency with the same precision as ours, but that's not going to scale particularly well, and it's a bit magical compared to being able to handle it as any other currency, perform conversions, etc.

**Additional context**

I don't think any is needed, but if I missed something, please let me know!

**Comment by alexdunae** [comment]
Another vote for this being useful.  We're using Dinero for custom "payment tokens" at events, each defined in their own currency at runtime.  Being able to define our own currencies would be hugely useful.

**Comment by sarahdayan** [comment]
Closing this in favor of #36. This will become possible in v2.
