### ISSUE TITLE
Enhancement - get currency by code

### ISSUE THREAD

**Issue by roco1234** [dinerojs/dinero.js#720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently you must import individual currencies for usage with dinero.

### Expected behavior

Request for functionality to get a currency by its code. To abstract dinero.js in a solution it would be useful to be able to send string types to get a Currency<number>

getCurrencyByCode(code: string): Currency<number>

### Steps to reproduce

dinero

### Version

2.0.0-alpha.13

### Environment

typescript

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnhooks** [comment]
The logic behind not having currency getter is explained in this issue https://github.com/dinerojs/dinero.js/issues/636.

**Comment by sarahdayan** [comment]
@roco1234 Having a built-in way to request any of the provided currencies by code would mean that you're loading all currency objects in your app, all the time. It's over 150 currencies, most of which you probably don't need!

Please refer to [this answer](https://github.com/dinerojs/dinero.js/issues/636#issuecomment-1304257279) to build your own mapping and fetch currencies dynamically.
