### ISSUE TITLE
Not async call .convert() for own provided rates

### ISSUE THREAD

**Issue by WojtylaCZ** [dinerojs/dinero.js#73]
**Is your feature request related to a problem? Please describe.**

I would find very convenient to stay in synchronous context when using the convert() method with own exchange rates. Without using a immediately resolving Promise.

**Describe the solution you'd like**

Add optional parameter to convert method for object with rates. It will work with CurrencyConverter as the Promise is only for API calls.

**Describe alternatives you've considered**

Manual conversion with multiplication and creating new Dinero object.

**Additional context**

Relates to #17 

Thank you for your work and the package. Great job! :)

**Comment by baskin** [comment]
Same requirement. In my case I use mobx managed exchange rates in a react environment. I'll be forced to run side effects (useEffect hooks etc..) to resolve a promise which I know resolves locally.

**Comment by sarahdayan** [comment]
Hey! I've just released [Dinero.js v2 alpha](https://v2.dinerojs.com/docs) with a much better design for conversions. You can provide rates directly, the responsibility of fetching them isn't coupled to the library.

You can check it out in the [API reference](https://v2.dinerojs.com/docs/api/conversions/convert).
