### ISSUE TITLE
Custom rounding modes

### ISSUE THREAD

**Issue by jonasesr** [dinerojs/dinero.js#74]
Currently there is no possibility to set up a custom rounding function. Therefore you are limited to the ones that are implemented by default. For my case I need a rounding function that always rounds up (e.g. 0.002 => 0.01 with precision 2, commercial rounding)

It would be nice to pass a callback or a string that describes the rounding mode. If it is a string and the string matches the supported ones, the matching function gets executed. If it is a callback, the callback gets executed.

**Comment by sarahdayan** [comment]
Hi @jonasesr! I'm totally open to a PR that implements this 🙂

This will be done like that in v2, but if you need it now, feel free.

**Comment by sarahdayan** [comment]
Hey there! I just released [Dinero.js v2 in alpha](https://v2.dinerojs.com/docs), and you no longer need to pass a rounding function when performing mutations.

You can still pass a rounding mode when formatting with [`toUnit`](https://v2.dinerojs.com/docs/api/formatting/to-unit) or [`toFormat`](https://v2.dinerojs.com/docs/api/formatting/to-format), and the library provides rounding functions for convenience. You can pass your own if you want to.

```js
import { dinero, toUnit } from 'dinero.js';
import { USD } from '@dinero.js/currencies';

const d = dinero({ amount: 10555, currency: USD, scale: 3 });

toUnit(d, { digits: 1, round: Math.round }); // 10.6
toUnit(d, { digits: 1, round: Math.floor }); // 10.5
toUnit(d, { digits: 2, round: Math.trunc }); // 10.55
```

You can see it in action [here](https://codesandbox.io/s/mystifying-easley-52s4j?file=/main.js).
