### ISSUE TITLE
[Bug]: Currencies missing human readable

### ISSUE THREAD

**Issue by atrauzzi** [dinerojs/dinero.js#758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Right now, all currencies [lack a human friendly label](https://github.com/dinerojs/dinero.js/blob/main/packages/currencies/src/iso4217/amendments/168/cad.ts).

### Expected behavior

There's actually a comment above each currency containing the exact text that I'd love to see made available.  Would like to see something like a "label" field or something similar added with that value.

### Steps to reproduce

N/A

### Version

N/A

### Environment

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karol-bujacek** [comment]
I am not sure that this is really a bug. Also consider that you may want the human readable label internationalized. Should the label be in English? Or should be the native language for currency be used? And if the currency is used in bilingual countries?
