### ISSUE TITLE
Allow allocate on null values

### ISSUE THREAD

**Issue by brasilikum** [dinerojs/dinero.js#83]
**Is your feature request related to a problem? Please describe.**

I want to use `allocate` on an array of numbers where some are 0.
I get the error that `TypeError: You must provide a non-empty array of numeric values greater than 0.`.
I understand that, because if all values would be zero, there would be no sensible way to do this operation.

I use this in the context of a cart, where I want to allocate a total earning relative to a per-item earning that can be 0.

**Describe the solution you'd like**

If I could pass an array where null values are explicitly ignored, like `[1, 2, null]`, that would make many operations I do a lot easier.
This would make the following operation possible:
```js
Dinero({amount: 3}).allocate([1, 2, null]) === [Dinero({amount: 2}, Dinero({amount: 4}, null]
```

**Describe alternatives you've considered**

I have to filter the array first and later re-add the elements at the right index.
Instead of `null`, this could also work on 0, but that would break backwards compatibility and also I think it's a good thing to make developers aware that allocating to all 0's is impossible.

I have written and tested the following helper functions. I run extract, on the non-zero items, allocate and run combine on with the result.
```ts

export const extractItemsIf = (
  filterFunction,
  items = []
): { extracted: any[]; withPlaceholders: any[] } => {
  const extracted: any[] = [];
  const withPlaceholders = items.map(item => {
    if (filterFunction(item)) {
      extracted.push(item);
      return null;
    }
    return item;
  });
  return { extracted, withPlaceholders };
};

export const combineItems = ({
  extracted = [],
  withPlaceholders = []
}): any[] => {
  const extractedRev: any[] = extracted.reverse();
  return withPlaceholders.map(item => (item ? item : extractedRev.pop()));
};
```

**Additional context**

I really love dinero.js, it makes my work a lot easier. It is obvious that a lot of thinking around handling money went into it so that users fo the library do not have to know all the edgecases. 
If this feature request is out of scope I totally understand. Thank you for considering.

**Comment by sarahdayan** [comment]
This enhancement indeed makes a lot of sense. However, I wouldn't allocate on null values, but on zero ratios. You can transform your null values into zero ratios, and Dinero will return instances with amount = 0. You could then use [`isZero`](https://dinerojs.com/module-dinero#~isZero) to filter back to `null`.

```js
const originalRatios = [1, 2, null];
const dineroRatios = originalRatios.map(ratio => Number(ratio));

const allocated = Dinero({ amount: 3 }).allocate(dineroRatios);

const allocatedWithoutZeroValues = allocated.map(d => (d.isZero() ? null : d));
```

Once merged and released, #85 will fix your issue 🙂
