### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by oreid01** [dinerojs/dinero.js#89]
The documentation website appears to be returning 404.

https://sarahdayan.github.io/dinero.js/

**Comment by cainaf** [comment]
i think it isn't down, it just changed domains: https://dinerojs.com/

i would recommend to the owner redirecting old website pages to relatives one in the new domain, if it's the case, to not be hurt in google page results ranking

**Comment by sarahdayan** [comment]
Hey, indeed I switched domains! I just added the redirect, so this should no longer return a 404.

Thanks for filing the issue!

**Comment by oreid01** [comment]
Thanks @sarahdayan!
